# Тема: Любовь
sex = "male/female"
orient = "natural/bi/gay/helicopter..."
age = "18..."
race = "American/Korean/Russian"
skin = "black/yellow/white"
col_hair = "blue/brown/black"
weight = "55..."
height = "180..."
voice = "cool/not cool"
singer = "True/False"

# Тема: Космос
galactic = "NGC 4414/NGC 7752"
stars = "1/2/3/4..."
planets = "1/2/3/4..."
moon = "1/2/3/4..."
life = "True/False"
meteor = "True/False"
main_element = "C/H2O..."
blackhole = "1/2/3/4..."
garbage = "True/False"
water = "True/False"

# Тема: Автомобили
name = "audi/BMW/Honda..."
max_torq = "1800H/m...."
wheels = "24/25..."
engine = "3/4/5..."
fuel = "92A/diesel/electro..."
gear_box = "3-4-5..."
air_cond = "True/False"
price = "10000$..."
spoiler = "True/False"
autopilot = "True/False"

# Тема: Природа
walk = "True/False"
swim = "True/False"
fly = "True/False"
type = "bird/human/animal/fish..."
food = "meat/grass/water..."
fur = "True/False"
nose = "True/False"
eyes = "True/False"
mouth = "True/False"
teeth = "True/False"

# Тема: Религия
status = "атеист/верующий"
type_of_religion = "Иудаизм/Христианство/Гностицизм/Ислам..."
form_of_religion = "Тотемизм/Шаманизм/Анимизм/Фетишизм"
extralife = "True/False"
reborn = "True/False"
hell = "True/False"
paradise = "True/False"
wear = "all/ordinary"
god = "True/False"
god_name = "Allah/Iisus/Budda..."